### ISSUE TITLE
Convert to servant-client

### ISSUE THREAD

**Issue by boj** [alasconnect/auth0#10]
@JBetz Hey, curious if you are still using this library?

We're in a place where we may finally end up using this library ourselves in the near future. I'm considering making a severe breaking change, which is to switch the whole thing over to [servant-client](https://hackage.haskell.org/package/servant-client) and provide a slightly different interface.

## Motivation

I didn't know about servant-client back when I wrote this. It provides a high level type safe set of routes and functions, which I consider to be a much better alternative to what I wrote. It would eliminate the weird `ToField` class and the custom Request module in favor of the more robust Servant way.

## (Non) Changes

- All of the JSON data structures stay the same
- All of the `run*` functions get replaced with `*` (so `runGetToken` becomes `getToken`), and new functions exist for variations, i.e. `getTokenPKCE`, `getTokenClientCreds`, `getTokenResourceOwner`
    - These are the actual functions which get called by `runClientM` from servant-client
    - This means all of the query params get passed in as parameters rather than a single data type as is currently done. This is so that they can map to proper Servant routes

For example, here is what Authentication.Login looks like now:

```haskell
type LoginApi
  = "authorize"
  :> QueryParam' '[Required] "response_type" ResponseType
  :> QueryParam' '[Required] "client_id" ClientId
  :> QueryParam "connection" Text
  :> QueryParam' '[Required]  "redirect_uri" Text
  :> QueryParam "state" Text
  -- :> QueryParams "additional" (Map Text Text)
  :> Get '[JSON] NoContent

loginApi :: Proxy LoginApi
loginApi = Proxy

login ::
     ResponseType
  -> ClientId
  -> Maybe Text
  -> Text
  -> Maybe Text
  -- -> [Map Text Text]
  -> ClientM NoContent

login = client loginApi
```

I will go back through and make type synonyms so each field is clearly named in the function header. Still looking into how to handle the "additional_parameters" bits.

## Conclusion

The actual changes are trivial to implement. This would introduce a breaking change to the current API. Since the package isn't on hackage, nor widely used as far as I know, it's probably not going to be a big problem.

If anyone else using this has thoughts, please weigh in.

**Comment by imalsogreg** [comment]
We have a half-baked Auth0 integration at work, also based on servant. It would be really nice to swap that out with your library, though of course we would like to keep the ability to generate clients and docs. So :+1: for this change.

**Comment by JBetz** [comment]
@boj Unfortunately no. My efforts to introduce a Haskell backend at my current job were sabotaged, and PureScript + node was used instead. I'm still interested in using this in the future, but probably not anytime soon. 

:+1: to the proposed changes.

**Comment by boj** [comment]
Great, thanks for the input @imalsogreg @JBetz 

@JBetz Sorry to hear you weren't able to get haskell going. PureScript is a nice step in the right direction at least.
